# Generated by Django 6.0.4 on 2026-05-06 19:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='UserPreferenceMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('text', models.TextField()),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('predicate', models.CharField(blank=True, max_length=128)),
                ('object', models.CharField(blank=True, max_length=255)),
                ('object_type', models.CharField(blank=True, max_length=128)),
                ('memory_type', models.CharField(choices=[('semantic', 'Semantic'), ('procedural', 'Procedural'), ('episodic', 'Episodic'), ('working', 'Working')], db_index=True, default='semantic', max_length=32)),
                ('confidence', models.FloatField(default=0.5)),
                ('importance', models.FloatField(default=0.5)),
                ('decay', models.FloatField(default=0.2)),
                ('reasoning', models.TextField(blank=True)),
                ('evidence', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('contradicted', 'Contradicted')], db_index=True, default='active', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='preferences_engine.memoryuser')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='UserPreferenceMemoryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('action', models.CharField(choices=[('extract', 'Extract'), ('create', 'Create'), ('reinforce', 'Reinforce'), ('merge', 'Merge'), ('contradict', 'Contradict'), ('ignore', 'Ignore')], db_index=True, max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('reasoning', models.TextField(blank=True)),
                ('evidence', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='preferences_engine.userpreferencememory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_events', to='preferences_engine.memoryuser')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='userpreferencememory',
            index=models.Index(fields=['user', 'status'], name='preferences_user_id_c97c7e_idx'),
        ),
        migrations.AddIndex(
            model_name='userpreferencememory',
            index=models.Index(fields=['user', 'conversation_id', 'status'], name='preferences_user_id_9c519b_idx'),
        ),
        migrations.AddIndex(
            model_name='userpreferencememory',
            index=models.Index(fields=['user', 'predicate', 'object'], name='preferences_user_id_18a372_idx'),
        ),
        migrations.AddIndex(
            model_name='userpreferencememory',
            index=models.Index(fields=['memory_type', 'status'], name='preferences_memory__c54e76_idx'),
        ),
        migrations.AddIndex(
            model_name='userpreferencememoryevent',
            index=models.Index(fields=['user', 'conversation_id', 'created_at'], name='preferences_user_id_183bc9_idx'),
        ),
        migrations.AddIndex(
            model_name='userpreferencememoryevent',
            index=models.Index(fields=['memory', 'created_at'], name='preferences_memory__a194f7_idx'),
        ),
        migrations.AddIndex(
            model_name='userpreferencememoryevent',
            index=models.Index(fields=['action', 'created_at'], name='preferences_action_841c7e_idx'),
        ),
    ]
